# Generated by Django 4.2.7 on 2024-01-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("piemonteData", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agente",
            name="cargo",
            field=models.CharField(default="agente", max_length=20),
        ),
        migrations.AddField(
            model_name="diretoria",
            name="cargo",
            field=models.CharField(default="diretor", max_length=20),
        ),
        migrations.AddField(
            model_name="gerencia",
            name="cargo",
            field=models.CharField(default="gerente", max_length=20),
        ),
        migrations.AddField(
            model_name="supervisao",
            name="cargo",
            field=models.CharField(default="supervisor(a)", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default=None, max_length=15),
        ),
    ]
