# Generated by Django 4.0 on 2023-11-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piemonteData', '0002_gerencia_diretoria_email_sent_supervisao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gerencia',
            old_name='diretor',
            new_name='diretoria',
        ),
    ]
