# Generated by Django 4.2.7 on 2024-01-17 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("piemonteData", "0002_agente_cargo_diretoria_cargo_gerencia_cargo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agente",
            name="diretoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="piemonteData.diretoria",
            ),
        ),
        migrations.AlterField(
            model_name="agente",
            name="gerencia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="piemonteData.gerencia",
            ),
        ),
        migrations.AlterField(
            model_name="agente",
            name="supervisor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="piemonteData.supervisao",
            ),
        ),
        migrations.AlterField(
            model_name="gerencia",
            name="diretoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="piemonteData.diretoria",
            ),
        ),
        migrations.AlterField(
            model_name="supervisao",
            name="cargo",
            field=models.CharField(default="supervisor", max_length=20),
        ),
        migrations.AlterField(
            model_name="supervisao",
            name="diretoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="piemonteData.diretoria",
            ),
        ),
        migrations.AlterField(
            model_name="supervisao",
            name="gerencia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="piemonteData.gerencia",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
