# Generated by Django 4.2.7 on 2023-12-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("piemonteData", "0003_rename_diretor_gerencia_diretoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="agente",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
