# Generated by Django 4.2.7 on 2024-01-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("piemonteData", "0003_alter_agente_diretoria_alter_agente_gerencia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="gerencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="piemonteData.gerencia",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nome",
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sobrenome",
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="supervisao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="piemonteData.supervisao",
            ),
        ),
    ]
