# Generated by Django 4.2.7 on 2024-01-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("piemonteData", "0004_userprofile_gerencia_userprofile_nome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nome",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="sobrenome",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
