# Generated by Django 4.2.7 on 2024-01-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("piemonteData", "0005_alter_userprofile_nome_alter_userprofile_sobrenome"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="root_id",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
