# Generated by Django 4.2.7 on 2024-01-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("piemonteData", "0007_alter_userprofile_root_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="agente", name="gerencia",),
    ]
