# Generated by Django 4.2.7 on 2024-01-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("piemonteData", "0008_remove_agente_gerencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="agente",
            name="gerencia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="piemonteData.gerencia",
            ),
        ),
    ]
